import React from 'react';
import Articles from '../components/Articles';

const articleResolver = {
    Aries:
        '<p >На карте изображен воин в красном развевающемся плаще с гладиаторским <a href="http://www.astrosymbols.ru/sword2"> <u>мечом</u> </a> и щитом в руках. Он бежит по пустынной дороге, оставив за собой разрушенный город, убитых им людей. На карте преобладает <a href="http://www.astrosymbols.ru/red"><u> красный цвет </u></a>, почти нет полутонов, что указывает на непримиримость и максимализм.</p><p >Образ воина символизирует активное мужское начало, которому соответствует импульсивность, активное самоутверждение, неосознанная агрессия, вызов. Мы видим, что он движется вперед несмотря ни на что, назад дороги нет. Воин одержим, прямолинеен, примитивен в проявлении, что подчеркнуто его простой одеждой.</p><p >Короткий гладиаторский <a href="http://www.astrosymbols.ru/sword2"> <u>меч</u> </a> указывает на неспособность к сложным стратегическим ходам. Его метод добиться желаемого – это решительный рывок, резкие действия.<br/>Щит в руках Воина украшен изображением зверя с агрессивной мордочкой. Девиз воина: &#171;Лучший способ защиты – это нападение&#187;.</p><h3 > <strong>Карта на день</strong></span></h3><p > <em><strong>Что для меня важнее всего сегодня сделать?<br/></strong></em> Это день активности, подъема внутренних сил. В этот день вам важно проявлять инициативу, действовать методом проб и ошибок. Необходимо самоутверждение.<br/> <em><strong>Что для меня важнее всего нужно сегодня понять?<br/></strong></em> Важнее всего понять, что гнев и агрессия не приводят к результату, а лишь опустошают вас энергетически.<br/> <em><strong>Чему я сегодня могу научиться?<br/></strong></em> Сегодня подходящий день, чтобы научиться контролировать себя, направить свою энергию в мирное русло.<br/> <em><strong>Что от меня сегодня хочет окружение?<br/></strong></em> От вас ждут инициативы и действия без промедления и проволочек. Если возникнет необходимость принять решение, не рубите с плеча.</p><p > <strong>Мотив</strong> – Завоевание, отстаивание. Стремление дать выход энергии, быть первым и единственным. Действие ради действия. Марш. Действия спонтанны. Я все знаю. Желание самостоятельности. Не учите меня жить, уйдите с моей дороги, я сам со всем справлюсь.</p><p > <strong>Состояние</strong> – Когда мы полны энергии, мы готовы действовать, для нас очень важно заявить о себе (может, даже, стукнуть кулаком по столу). Мы не боимся идти на конфликт, рвемся в бой, &#171;покой нам только снится&#187;.</p><p > <strong>Процесс</strong> – Будет протекать бурно, импульсивно, но непродолжительно.</p><p > <strong>Результат</strong> – Карта говорит о возможности одержать победу, настоять на своем, опередить что-то, захватить, но победа будет недолгой, кратковременной.</p><p > <strong>Отношения</strong> – Очень интенсивно протекающие, бурные, сексуально ярко окрашенные. В этих отношениях прослеживается тема лидерства. Так как карта мужская, то важная роль при рассмотрении отношений отводится именно мужчине. Африканские страсти, стремление быть лидером, завоевание. Ревность или конкуренция. Мнение другого человека в расчет не берется. Нестабильность отношений. Готовность смены партнера.</p><p > <strong>Предостережение</strong> – Поспешность в действиях, не продуманность. Не зная брода, не ломай мосты. Прежде чем входить в ситуацию, подумай, как будешь из нее выходить.</p><p > <strong>Совет</strong> – Действовать открыто, напрямую, быстро, не откладывая. Быть первым. Бороться за победу. &#171;Промедление смерти подобно&#187;.</p>',
    AriesTaurus: <Articles.AriesTaurus />,
    AriesGemini: <Articles.AriesGemini />,
    AriesCancer: <Articles.AriesCancer />,
    AriesLeo: <Articles.AriesLeo />,
    AriesVirgo: <Articles.AriesVirgo />,
    AriesLibra: <Articles.AriesLibra />,
    AriesScorpio: <Articles.AriesScorpio />,
    AriesSagittarius: <Articles.AriesSagittarius />,
    AriesCapricorn: <Articles.AriesCapricorn />,
    AriesAquarius: <Articles.AriesAquarius />,
    AriesPisces: <Articles.AriesPisces />,
    Taurus: <Articles.Taurus />,
    TaurusGemini: <Articles.TaurusGemini />,
    TaurusCancer: <Articles.TaurusCancer />,
    TaurusLeo: <Articles.TaurusLeo />,
    TaurusVirgo: <Articles.TaurusVirgo />,
    TaurusLibra: <Articles.TaurusLibra />,
    TaurusScorpio: <Articles.TaurusScorpio />,
    TaurusSagittarius: <Articles.TaurusSagittarius />,
    TaurusCapricorn: <Articles.TaurusCapricorn />,
    TaurusAquarius: <Articles.TaurusAquarius />,
    TaurusPisces: <Articles.TaurusPisces />,
    Gemini: <Articles.Gemini />,
    GeminiCancer: <Articles.GeminiCancer />,
    GeminiLeo: <Articles.GeminiLeo />,
    GeminiVirgo: <Articles.GeminiVirgo />,
    GeminiLibra: <Articles.GeminiLibra />,
    GeminiScorpio: <Articles.GeminiScorpio />,
    GeminiSagittarius: <Articles.GeminiSagittarius />,
    GeminiCapricorn: <Articles.GeminiCapricorn />,
    GeminiAquarius: <Articles.GeminiAquarius />,
    GeminiPisces: <Articles.GeminiPisces />,
    Cancer: <Articles.Cancer />,
    CancerLeo: <Articles.CancerLeo />,
    CancerVirgo: <Articles.CancerVirgo />,
    CancerLibra: <Articles.CancerLibra />,
    CancerScorpio: <Articles.CancerScorpio />,
    CancerSagittarius: <Articles.CancerSagittarius />,
    CancerCapricorn: <Articles.CancerCapricorn />,
    CancerAquarius: <Articles.CancerAquarius />,
    CancerPisces: <Articles.CancerPisces />,
    Leo: <Articles.Leo />,
    LeoVirgo: <Articles.LeoVirgo />,
    LeoLibra: <Articles.LeoLibra />,
    LeoScorpio: <Articles.LeoScorpio />,
    LeoSagittarius: <Articles.LeoSagittarius />,
    LeoCapricorn: <Articles.LeoCapricorn />,
    LeoAquarius: <Articles.LeoAquarius />,
    LeoPisces: <Articles.LeoPisces />,
    Virgo: <Articles.Virgo />,
    VirgoLibra: <Articles.VirgoLibra />,
    VirgoScorpio: <Articles.VirgoScorpio />,
    VirgoSagittarius: <Articles.VirgoSagittarius />,
    VirgoCapricorn: <Articles.VirgoCapricorn />,
    VirgoAquarius: <Articles.VirgoAquarius />,
    VirgoPisces: <Articles.VirgoPisces />,
    Libra: <Articles.Libra />,
    LibraScorpio: <Articles.LibraScorpio />,
    LibraSagittarius: <Articles.LibraSagittarius />,
    LibraCapricorn: <Articles.LibraCapricorn />,
    LibraAquarius: <Articles.LibraAquarius />,
    LibraPisces: <Articles.LibraPisces />,
    Scorpio: <Articles.Scorpio />,
    ScorpioSagittarius: <Articles.ScorpioSagittarius />,
    ScorpioCapricorn: <Articles.ScorpioCapricorn />,
    ScorpioAquarius: <Articles.ScorpioAquarius />,
    ScorpioPisces: <Articles.ScorpioPisces />,
    Sagittarius: <Articles.Sagittarius />,
    SagittariusCapricorn: <Articles.SagittariusCapricorn />,
    SagittariusAquarius: <Articles.SagittariusAquarius />,
    SagittariusPisces: <Articles.SagittariusPisces />,
    Capricorn: <Articles.Capricorn />,
    CapricornAquarius: <Articles.CapricornAquarius />,
    CapricornPisces: <Articles.CapricornPisces />,
    Aquarius: <Articles.Aquarius />,
    AquariusPisces: <Articles.AquariusPisces />,
    Pisces: <Articles.Pisces />,
    BlankPage: 'BlankPage',
};

export default articleResolver;
