const { ARTICLE_QUERY } = require('./ARTICLE_QUERY');

const { SELECTED_CARDS_QUERY } = require('./SELECTED_CARDS_QUERY');
const { UPDATE_VARIABLE_MUTATION } = require('./UPDATE_VARIABLE_MUTATION');
const { VARIABLE_QUERY } = require('./VARIABLE_QUERY');
const { UPDATE_ARTICLE_MUTATION } = require('./UPDATE_ARTICLE_MUTATION');
const { UPDATE_CARDS_MUTATION } = require('./UPDATE_CARDS_MUTATION');

const queries = [
    ARTICLE_QUERY,

    SELECTED_CARDS_QUERY,
    UPDATE_VARIABLE_MUTATION,
    VARIABLE_QUERY,
    UPDATE_ARTICLE_MUTATION,
    UPDATE_CARDS_MUTATION,
];

module.exports = {
    queries,
};
