import ARTICLE_QUERY from './ARTICLE_QUERY';
import SELECTED_CARDS_QUERY from './SELECTED_CARDS_QUERY';
import UPDATE_CARDS_MUTATION from './UPDATE_CARDS_MUTATION';

const queries = [ARTICLE_QUERY, SELECTED_CARDS_QUERY, UPDATE_CARDS_MUTATION];

export default queries;
